#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Provisions the route to the cavbot2 panel for wayfinder ticket #261.
# Run it on the production host from the cavbot2 compose directory:
#
#   cd /path/to/cavbot2 && ./provision-panel-host.sh
#
# The env var names below are provisional. The temp VC spec fixes them.

PANEL_HOST="cavbot2.7cav.us"
PANEL_PORT="8080"
CALLBACK_PATH="/auth/callback"
DOCKER_NETWORK="edge"
FORUM_URL="https://7cav.us"

TOTAL_STAGES=5

banner "cavbot2 panel host"

# ── Stage 1: preflight on the host ────────────────────────────────────────
stage "Preflight on the host"
say "Two stages edit files and inspect Docker, so this must run on the production host."
if [[ ! -f docker-compose.yml ]]; then
  warn "no docker-compose.yml here. cd to the cavbot2 compose directory and re-run."
  exit 1
fi
if ! command -v docker >/dev/null 2>&1; then
  warn "docker is not on PATH. Run this on the production host."
  exit 1
fi
if docker network inspect "$DOCKER_NETWORK" --format '{{.Name}} ({{.Driver}})' 2>/dev/null; then
  say "Network $DOCKER_NETWORK exists. NPM reaches the bot over it once the compose file declares it."
else
  warn "network $DOCKER_NETWORK not found. Check 'docker network ls' for the one NPM shares with proxied services."
  exit 1
fi
note "The compose change (add $DOCKER_NETWORK as an external network on the cavbot2 service) lands with the panel PR, not now."
pause

# ── Stage 2: Cloudflare tunnel hostname ───────────────────────────────────
stage "Cloudflare: public hostname on the tunnel"
open_url "https://one.dash.cloudflare.com/"
step "Networks > Tunnels > the tunnel that serves the other 7cav.us hosts > Configure."
step "Public Hostname tab > Add a public hostname."
step "Subdomain: cavbot2. Domain: 7cav.us. Path: empty."
step "Service type and URL: copy them from an existing hostname on this tunnel. They point at NPM."
step "Save the hostname."
note "If the tunnel is configured from a config file instead of the dashboard, add the same ingress rule there and restart cloudflared."
pause "Saved?"
write_env PANEL_BASE_URL "https://${PANEL_HOST}"

# ── Stage 3: Nginx Proxy Manager proxy host ───────────────────────────────
stage "Nginx Proxy Manager: proxy host"
say "Open the NPM admin UI in your browser."
step "Hosts > Proxy Hosts > Add Proxy Host."
step "Domain Names: ${PANEL_HOST}."
step "Scheme: http. Forward Hostname / IP: cavbot2. Forward Port: ${PANEL_PORT}."
step "Block Common Exploits: on. Websockets Support: off."
step "SSL tab: match the other proxy hosts served through the tunnel."
step "Save."
note "The bot has no panel yet, so this host returns 502 until the panel PR ships. That is expected."
pause "Saved?"
write_env PANEL_ADDR ":${PANEL_PORT}"

# ── Stage 4: forum OAuth2 client ──────────────────────────────────────────
stage "Forum: register the OAuth2 client"
open_url "${FORUM_URL}/admin.php?oauth2/clients"
step "Add client."
step "Title: cavbot2 panel."
step "Client type: Confidential."
step "Redirect URIs, one per line, exactly as written:"
say "    https://${PANEL_HOST}${CALLBACK_PATH}"
say "    http://localhost${CALLBACK_PATH}"
note "The second one matches any port on localhost, so local runs need no forum change."
step "Scopes: tick user:read and user:groups."
if ! confirm "Is user:groups in the scope list?"; then
  warn "The Cav7/UserGroupsScope add-on is not installed on production. Sign-in will work but no groups arrive."
  SKIPPED+=("Install Cav7/UserGroupsScope on production, then tick user:groups on the cavbot2 panel client")
fi
step "Active: on. Save."
step "On the saved client, copy the Client ID, then reveal and copy the Client secret."
ask PANEL_OAUTH_CLIENT_ID "Client ID:"
ask_secret PANEL_OAUTH_CLIENT_SECRET "Client secret (hidden):"
write_env PANEL_OAUTH_CLIENT_ID "$PANEL_OAUTH_CLIENT_ID"
write_env PANEL_OAUTH_CLIENT_SECRET "$PANEL_OAUTH_CLIENT_SECRET"

# ── Stage 5: forum endpoint URLs ──────────────────────────────────────────
stage "Forum: endpoint URLs"
say "Still on the client page. The form prints three endpoint URLs above the redirect URIs."
say "Copy each one as shown. The friendly URL setting decides their shape, so do not retype them."
ask PANEL_OAUTH_AUTHORIZE_URL "Authorization endpoint:"
ask PANEL_OAUTH_TOKEN_URL "Token endpoint:"
ask PANEL_OAUTH_REVOKE_URL "Token revocation endpoint:"
write_env PANEL_OAUTH_AUTHORIZE_URL "$PANEL_OAUTH_AUTHORIZE_URL"
write_env PANEL_OAUTH_TOKEN_URL "$PANEL_OAUTH_TOKEN_URL"
write_env PANEL_OAUTH_REVOKE_URL "$PANEL_OAUTH_REVOKE_URL"
note "Report back for the ticket: port ${PANEL_PORT}, network ${DOCKER_NETWORK}, callback ${CALLBACK_PATH}, credentials in $(pwd)/${ENV_FILE}."
# ──────────────────────────────────────────────────────────────────────────

finish
